parameters: {}
environment:
  SITE_URL: ${SITE_URL}
  SITE_TITLE: ${SITE_TITLE}
packages:
    - name: main
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: reverse
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
